# Generated by Django 2.0 on 2019-04-21 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Select_Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Month', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='select_month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Year'),
        ),
    ]
