# Generated by Django 2.0 on 2019-04-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='scaton',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.class_section'),
            preserve_default=False,
        ),
    ]
