# Generated by Django 2.0 on 2019-04-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_studentinfo_scaton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='scaton',
            new_name='scation',
        ),
    ]
